import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import Homelink from '@/components/homelink'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Qadir Corp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={`${styles.main} ${inter.className}`}>
        <Homelink linkname="Qadir Corp"/>

        <div className={styles.center}>
          <Image
            className={styles.left_icon}
            src="/robotics_icon1.png"
            alt="Robotics Icon"
            width={80}
            height={80}
            priority
          />
          <div className={styles.titleBlock}>
            <p className={styles.title}>Qadir Corporation</p>
            <p className={styles.subtitle}>Design For The Future</p>
          </div>
          <Image
            className={styles.right_icon}
            src="/robotics_icon.png"
            alt="Robotics Icon"
            width={80}
            height={80}
            priority
          />
        </div>

        <div className={styles.grid}>
          <Link
            href="/about"
            className={styles.card}
          >
            <h2>
              About <span>-&gt;</span>
            </h2>
            <p>
              More about Qadir Corporation and members!
            </p>
          </Link>

          <Link
            href="/about"
            className={styles.card}
          >
            <h2>
              Service <span>-&gt;</span>
            </h2>
            <p>
              More about Qadir Corporation and members!
            </p>
          </Link>

          <Link
            href="/about"
            className={styles.card}
          >
            <h2>
              Past Cases <span>-&gt;</span>
            </h2>
            <p>
              More about Qadir Corporation and members!
            </p>
          </Link>
        </div>
      </main>
      <Footer/>
    </>
  )
}
