import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Navbar from '@/components/navbar.js'
import Footer from '@/components/footer.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Qadir Corp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={`${styles.main} ${inter.className}`}>
        <Link className={styles.home_link} href={"/"}>
          QADIR CORP
        </Link>

        <div className={styles.center}>
          <Image
            className={styles.left_icon}
            src="/robotics_icon1.png"
            alt="Robotics Icon"
            width={80}
            height={80}
            priority
          />
          <div className={styles.titleBlock}>
            <p className={styles.title}>Qadir Corporation</p>
            <p className={styles.subtitle}>Design For The Future</p>
          </div>
          <Image
            className={styles.right_icon}
            src="/robotics_icon.png"
            alt="Robotics Icon"
            width={80}
            height={80}
            priority
          />
        </div>

        <div className={styles.grid}>
          <Link
            href="/about"
            className={styles.card}
          >
            <h2>
              About <span>-&gt;</span>
            </h2>
            <p>
              More about Qadir Corporation and members!
            </p>
          </Link>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
      <Footer/>
    </>
  )
}
